id: P9F60F4CF
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: fr
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    645374a51b0c45e09a260ea1c2eb4585:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    467b1a021bf84baea9be837327a457db:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    bfcc6c2de7cc490ba167e22af8e2413c:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    3274f0f2c95340c1a887ee2c712956ab:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    5e048ebb3e76473093239ffdda25f2ee:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    cd711c1c26c1448197a556f3cb29b93e:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    44850002690c45cf89f617b1b7a1113d:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    3fc9d8df9a6448d5b735db964efcdeee:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    1906df2ea1044c2595b49b2dc79a03e1:
      title: The Lament of Rudra
      parent: Confession
    87dea1f1defc42c1a16c9a60d9f37cf1:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    4f90a22fe41749aabcd004415b3ccf5a:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    62ff104982274f49b98dcb42c8db49c8:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    430cd44091a24f208e3e06447c3ba5be:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    b61ffc9925594c3db13c5940e0725c60:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    2b52e85b9dd24b14a0427c9fadd153d9:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    dc791599b0fd43cab17bfdc33c9ac71c:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    b1881cb4d5484f85bb280f4a81cdb19f:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    4fb349cc5a9f42bb850fb11596e0f28c:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    1d95e9fa1c704898911c6e0913dc1d6d:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.993818'
last_modified_at: '2022-03-01T03:13:53.993821'
